# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 01:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_remove_meal_last_selected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 2, 1, 46, 56, 871000, tzinfo=utc)),
        ),
    ]
