# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_history_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
