# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 01:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_auto_20160601_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='update_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 4, 1, 34, 37, 968000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_name',
            field=models.CharField(max_length=255),
        ),
    ]
