# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 02:35
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('meals', '0006_auto_20160603_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
