# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_meal_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'history-type',
                'verbose_name_plural': 'history-types',
            },
        ),
        migrations.RemoveField(
            model_name='history',
            name='history_type',
        ),
        migrations.AddField(
            model_name='history',
            name='history_type',
            field=models.ManyToManyField(blank=True, to='meals.HistoryType'),
        ),
    ]
