# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_auto_20160603_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='history_type',
        ),
        migrations.AddField(
            model_name='history',
            name='history_type',
            field=models.CharField(choices=[('Sug', 'Suggested'), ('Sel', 'Selected')], default='Sug', max_length=50),
        ),
    ]
