# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_auto_20160604_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='history_type',
            field=models.CharField(choices=[('Suggested', 'Suggested'), ('Selected', 'Selected')], default='Suggested', max_length=50),
        ),
    ]
