# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_meal_last_selected_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='last_selected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='last_suggested_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
